# Generated by Django 4.2.28 on 2026-02-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaVocacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "color_hex",
                    models.CharField(
                        default="#3498db",
                        help_text="Color para visualización",
                        max_length=7,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categorías Vocacionales",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EvaluacionVocacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("iniciada", "Iniciada"),
                            ("en_progreso", "En progreso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="iniciada",
                        max_length=20,
                    ),
                ),
                ("ip_usuario", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("iniciado_en", models.DateTimeField(auto_now_add=True)),
                ("completado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos extra: navegador, resolución, etc.",
                    ),
                ),
            ],
            options={
                "ordering": ["-iniciado_en"],
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "tipo_respuesta",
                    models.CharField(
                        choices=[
                            ("boolean", "Sí/No"),
                            ("escala", "Escala 1-5"),
                            ("opcion_multiple", "Opción múltiple"),
                        ],
                        default="boolean",
                        max_length=20,
                    ),
                ),
                (
                    "opciones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Opciones para tipo 'opcion_multiple' o 'escala'",
                    ),
                ),
                (
                    "peso_categoria",
                    models.FloatField(
                        default=1.0, help_text="Peso de esta pregunta para su categoría"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preguntas",
                        to="api_vocacional.categoriavocacional",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_respuesta",
                    models.JSONField(
                        help_text="Puede ser string, número, boolean o objeto"
                    ),
                ),
                (
                    "tiempo_respuesta_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Tiempo que tardó en responder", null=True
                    ),
                ),
                ("respondido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="api_vocacional.evaluacionvocacional",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api_vocacional.pregunta",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["evaluacion", "pregunta"],
                        name="api_vocacio_evaluac_678609_idx",
                    )
                ],
                "unique_together": {("evaluacion", "pregunta")},
            },
        ),
        migrations.AddIndex(
            model_name="pregunta",
            index=models.Index(
                fields=["categoria", "activa"], name="api_vocacio_categor_8af67e_idx"
            ),
        ),
    ]
