# Generated by Django 6.0.2 on 2026-03-24 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_vocacional",
            "0003_programaestatal_alter_evaluacionvocacional_usuario_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfilacademico",
            options={"ordering": ["-id"], "verbose_name_plural": "Perfiles Académicos"},
        ),
        migrations.RemoveField(
            model_name="perfilacademico",
            name="creado_en",
        ),
        migrations.RemoveField(
            model_name="perfilacademico",
            name="institucion",
        ),
        migrations.RemoveField(
            model_name="perfilacademico",
            name="nivel_educativo",
        ),
        migrations.RemoveField(
            model_name="perfilacademico",
            name="usuario",
        ),
        migrations.AddField(
            model_name="perfilacademico",
            name="evaluacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfiles_academicos",
                to="api_vocacional.evaluacionvocacional",
            ),
        ),
        migrations.AddField(
            model_name="perfilacademico",
            name="pregunta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfiles_academicos",
                to="api_vocacional.pregunta",
            ),
        ),
        migrations.DeleteModel(
            name="FactoresSocioeconomicos",
        ),
    ]
